site_name: Knowledge Base
site_url: https://wiki.romanroth.net
repo_url: https://github.com/romanroth/KnowledgeBase
repo_name: romanroth/KnowledgeBase
docs_dir: Docs
plugins:
  - material-plausible

extra:
  analytics:
    provider: plausible
    domain: wiki.romanroth.net
    #: If using custom domain proxy or self-hosting Plausible,
    #: uncomment and specify script path here:
    src: "https://plausible.romanroth.net/js/script.js"
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
theme: 
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    - scheme: light
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: dark
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
