site_name: Knowledge Base
site_url: https://wiki.romanroth.net
repo_url: https://github.com/romanroth/KnowledgeBase
repo_name: romanroth/KnowledgeBase
edit_uri: edit/main/docs/
docs_dir: docs
plugins:
  - search
  - material-plausible
  - git-revision-date-localized:
      enable_creation_date: true
      type: custom
      custom_format: "%d. %B %Y"
  - tags:
      tags_file: tags.md
extra:
  analytics:
    provider: plausible
    domain: wiki.romanroth.net
    #: If using custom domain proxy or self-hosting Plausible,
    #: uncomment and specify script path here:
    src: "https://plausible.romanroth.net/js/script.js"
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
theme: 
  name: material
  custom_dir: mkdocs/overrides
  features:
     - navigation.top
     - content.action.edit
     - content.action.view
     #- navigation.tabs
  icon:
    repo: fontawesome/brands/git-alt
    edit: material/pencil
    view: material/eye
  palette:
    - scheme: light
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: dark
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
