site_name: Knowledge Base
site_url: https://wiki.romanroth.net
docs_dir: Docs
#extra_css:
  #- stylesheets/extra.css
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
theme: 
  name: material
  theme:
  palette:
    # Palette toggle for light mode
    - scheme: light
      # primary: orange
      # accent: orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: dark
      # primary: orange
      # accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
